import localFont from 'next/font/local';
import "./globals.css";

const basicFont = localFont({
  src: './font/ClashGrotesk-Regular.woff',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={basicFont.className}>{children}</body>
    </html>
  );
}
